networks:
  torrent_default:
    external: true
    name: "torrent_default"
  proxy-netwerk:
    external: true

services:
  wireguard:
    container_name: wireguard
    image: thrnz/docker-wireguard-pia:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - USER=${PIA_USER}
      - PASS=${PIA_PASS}
      - LOC=${PIA_LOCATION}
      - LOCAL_NETWORK=${LOCAL_NETWORK}
    volumes:
      - pia:/pia
      - pia-shared:/pia-shared
    ports:
      - "8088:8080" # qBittorrent WebUI
      - "9697:9696" # Prowlarr WebUI
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      - torrent_default
      - proxy-netwerk
    healthcheck:
      test: ["CMD-SHELL", "ping -c 1 1.1.1.1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  qbittorrent:
    container_name: "qbittorrent"
    image: "lscr.io/linuxserver/qbittorrent:4.6.7"
    network_mode: "service:wireguard"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - "${DOCKER_BASE_PATH}/torrent/qbittorrent:/config"
      - "${DATA_BASE_PATH}:/data"
      - "${SAMBA_PATH}:/samba"
    depends_on:
      wireguard:
        condition: service_healthy
    restart: "unless-stopped"

  prowlarr:
    container_name: "prowlarr"
    image: "lscr.io/linuxserver/prowlarr:latest"
    network_mode: "service:wireguard"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${DOCKER_BASE_PATH}/torrent/prowlarr:/config"
    depends_on:
      wireguard:
        condition: service_healthy
    restart: "unless-stopped"

  flaresolverr:
    container_name: "flaresolverr"
    image: "ghcr.io/flaresolverr/flaresolverr:latest"
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    networks:
      - "torrent_default"
    restart: "unless-stopped"

  cross-seed:
    container_name: "cross-seed"
    image: "ghcr.io/cross-seed/cross-seed:latest"
    command: ["daemon"]
    networks:
      - "torrent_default"
    ports:
      - "2468:2468"
    volumes:
      - "${DOCKER_BASE_PATH}/torrent/cross-seed:/config"
      - "${DATA_BASE_PATH}:/data"
    restart: "unless-stopped"

  deunhealth:
    container_name: "deunhealth"
    image: "qmcgaw/deunhealth"
    network_mode: "none"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: "always"

volumes:
  pia:
  pia-shared: