networks:
  proxy-netwerk:
    external: true
    name: "proxy-netwerk"

services:
  # pihole:
  #   container_name: pihole
  #   image: pihole/pihole:latest
  #   ports:
  #     # DNS Ports
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #     # Default HTTP Port
  #     - "8008:80/tcp"
  #     # Default HTTPs Port. FTL will generate a self-signed certificate
  #     - "7443:443/tcp"
  #   environment:
  #     TZ: 'Europe/Amsterdam'
  #     FTLCONF_webserver_api_password: 'd7StnU0W!ENHL9oi'
  #     FTLCONF_dns_listeningMode: 'all'

  #   volumes:
  #     - './etc-pihole:/etc/pihole'
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_TIME
  #     - SYS_NICE
  #   restart: unless-stopped

  nginx-proxy-manager:
    container_name: "nginx-proxy-manager"
    image: "jc21/nginx-proxy-manager:latest"
    networks:
      - "proxy-netwerk"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - "${DOCKER_BASE_PATH}/nginx/data:/data"
      - "${DOCKER_BASE_PATH}/nginx/letsencrypt:/etc/letsencrypt"
    restart: "unless-stopped"

  syncthing:
    container_name: syncthing
    image: lscr.io/linuxserver/syncthing:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_BASE_PATH}/syncthing:/config
      - ${DATA_BASE_PATH}:/data/sync # Voorbeeld-pad voor je data
    ports:
      - "8384:8384"     # WebUI poort
      - "22000:22000/tcp" # Data-overdracht poort
      - "21027:21027/udp" # Discovery poort
    networks:
      - proxy-netwerk

volumes:
  portainer_data:
    external: true