networks:
  proxy-netwerk:
    external: true
    name: "proxy-netwerk"

services:
  # portainer:
  #   container_name: "portainer"
  #   image: "portainer/portainer-ce:lts"
  #   ports:
  #     - "8000:8000"
  #     - "9443:9443"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #     - "portainer_data:/data"
  #   restart: "always"

  nginx-proxy-manager:
    container_name: "nginx-proxy-manager"
    image: "jc21/nginx-proxy-manager:2.12.3"
    networks:
      - "proxy-netwerk"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - "${DOCKER_BASE_PATH}/nginx/data:/data"
      - "${DOCKER_BASE_PATH}/nginx/letsencrypt:/etc/letsencrypt"
    restart: "unless-stopped"

volumes:
  portainer_data:
    external: true