networks:
  proxy-netwerk:
    external: true
    name: "proxy-netwerk"

services:
  # pihole:
  #   container_name: pihole
  #   image: pihole/pihole:latest
  #   ports:
  #     # DNS Ports
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #     # Default HTTP Port
  #     - "8008:80/tcp"
  #     # Default HTTPs Port. FTL will generate a self-signed certificate
  #     - "7443:443/tcp"
  #   environment:
  #     TZ: 'Europe/Amsterdam'
  #     FTLCONF_webserver_api_password: 'd7StnU0W!ENHL9oi'
  #     FTLCONF_dns_listeningMode: 'all'

  #   volumes:
  #     - './etc-pihole:/etc/pihole'
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_TIME
  #     - SYS_NICE
  #   restart: unless-stopped
  
  cloudflared:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiYWE4YTVlZDQyNGZmMTBiMDQ5ODFkZWExNzRhOTE4MzgiLCJ0IjoiZDk0ZTYyOWMtNzhkNC00YjA3LTgyMTAtNTU4YjYyYjc0ZDJiIiwicyI6Ik5URTNORGcxT0RrdE9EUXhNaTAwT1ROakxUbGtZemN0WlRaall6SXpNRGMyWVdOaiJ9
    networks:
      - proxy-netwerk

  nginx-proxy-manager:
    container_name: "nginx-proxy-manager"
    image: "jc21/nginx-proxy-manager:latest"
    networks:
      - "proxy-netwerk"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - "${DOCKER_BASE_PATH}/nginx/data:/data"
      - "${DOCKER_BASE_PATH}/nginx/letsencrypt:/etc/letsencrypt"
    restart: "unless-stopped"

volumes:
  portainer_data:
    external: true