networks:
  proxy-netwerk:
    external: true
    name: "proxy-netwerk"

services:
  nginx-proxy-manager:
    container_name: "nginx-proxy-manager"
    image: "jc21/nginx-proxy-manager:latest"
    networks:
      - "proxy-netwerk"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - "${DOCKER_BASE_PATH}/nginx/data:/data"
      - "${DOCKER_BASE_PATH}/nginx/letsencrypt:/etc/letsencrypt"
    restart: "unless-stopped"

volumes:
  portainer_data:
    external: true