networks:
  player_default:
    external: true
    name: "player_default"

services:
  jellyfin:
    container_name: "jellyfin"
    image: "jellyfin/jellyfin:latest"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - "player_default"
    ports:
      - "8096:8096"
    volumes:
      - "${DOCKER_BASE_PATH}/player/jellyfin:/config"
      - "${DATA_BASE_PATH}:/data"
      - "${SAMBA_PATH}:/samba"
      - "61892c2d44b50d79a6f11a5ba095f04347a7290905658f5856ab6c363a199c55:/cache"
    restart: "unless-stopped"

  plex:
    container_name: "plex"
    image: "lscr.io/linuxserver/plex:latest"
    network_mode: "host"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - "${DOCKER_BASE_PATH}/player/plex:/config"
      - "${DATA_BASE_PATH}:/data"
      - "${SAMBA_PATH}:/samba"
    restart: "unless-stopped"

  # tautulli:
  #   container_name: "tautulli"
  #   image: "ghcr.io/tautulli/tautulli:latest"
  #   restart: unless-stopped
  #   network_mode: "host"
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #   volumes:
  #     - "${DOCKER_BASE_PATH}/player/tautulli:/config"

volumes:
  61892c2d44b50d79a6f11a5ba095f04347a7290905658f5856ab6c363a199c55:
    external: true