networks:
  arr_default:
    external: true
    name: "arr_default"

services:
  # makemkv:
  #   container_name: "makemkv"
  #   image: "jlesage/makemkv:latest"
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #   ports:
  #     - "5800:5800" # Optionele poort voor de web-interface
  #   volumes:
  #     - "${SAMBA_PATH}/remux/watch:/watch"
  #     - "${SAMBA_PATH}/remux/output:/output"
  #     - "${DOCKER_BASE_PATH}/arr/makemkv:/config"
  #   restart: "unless-stopped"

  lidarr:
    container_name: "lidarr"
    image: "lscr.io/linuxserver/lidarr:latest"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - "arr_default"
    ports:
      - "8686:8686"
    volumes:
      - "${DOCKER_BASE_PATH}/arr/lidarr:/config"
      - "${DATA_BASE_PATH}:/data"
    restart: "unless-stopped"

  # radarr3D:
  #   container_name: "radarr 3D"
  #   image: "lscr.io/linuxserver/radarr:latest"
  #   environment:
  #     - TZ=${TZ}
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #   networks:
  #     - "arr_default"
  #   ports:
  #     - "7979:7979"
  #   volumes:
  #     - "${DOCKER_BASE_PATH}/arr/radarr 3D:/config"
  #     - "${DATA_BASE_PATH}:/data"
  #     - "${SAMBA_PATH}:/samba"
  #   restart: "unless-stopped"

  radarr:
    container_name: "radarr"
    image: "lscr.io/linuxserver/radarr:latest"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - "arr_default"
    ports:
      - "7878:7878"
    volumes:
      - "${DOCKER_BASE_PATH}/arr/radarr:/config"
      - "${DATA_BASE_PATH}:/data"
      - "${SAMBA_PATH}:/samba"
    restart: "unless-stopped"

  sonarr:
    container_name: "sonarr"
    image: "lscr.io/linuxserver/sonarr:latest"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - "arr_default"
    ports:
      - "8989:8989"
    volumes:
      - "${DOCKER_BASE_PATH}/arr/sonarr:/config"
      - "${DATA_BASE_PATH}:/data"
    restart: "unless-stopped"

  whisparr:
    container_name: "whisparr"
    image: "lscr.io/linuxserver/whisparr:latest"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - "arr_default"
    ports:
      - "6969:6969"
    volumes:
      - "${DOCKER_BASE_PATH}/arr/whisparr:/config"
      - "${DATA_BASE_PATH}:/data"
    restart: "unless-stopped"