networks:
  arr_default:
    external: true
    name: "arr_default"

services:
  lidarr:
    container_name: "lidarr"
    image: "lscr.io/linuxserver/lidarr:latest"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - "arr_default"
    ports:
      - "8686:8686"
    volumes:
      - "${DOCKER_BASE_PATH}/arr/lidarr:/config"
      - "${DATA_BASE_PATH}:/data"
    restart: "unless-stopped"

  radarr:
    container_name: "radarr"
    build: ./radarr-custom
    #image: "lscr.io/linuxserver/radarr:latest"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - "arr_default"
    ports:
      - "7878:7878"
    volumes:
      - "${DOCKER_BASE_PATH}/arr/radarr:/config"
      - "${DATA_BASE_PATH}:/data"
      - "${SAMBA_PATH}:/samba"
    restart: "unless-stopped"

  sonarr:
    container_name: "sonarr"
    image: "lscr.io/linuxserver/sonarr:latest"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - "arr_default"
    ports:
      - "8989:8989"
    volumes:
      - "${DOCKER_BASE_PATH}/arr/sonarr:/config"
      - "${DATA_BASE_PATH}:/data"
    restart: "unless-stopped"