version: "3.6"

networks:
  arr_default:
    external: true
    name: "arr_default"

services:
  lidarr:
    container_name: "lidarr"
    image: "lscr.io/linuxserver/lidarr:2.12.4.4658-ls45"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - "arr_default"
    ports:
      - "8686:8686"
    volumes:
      - "${DOCKER_BASE_PATH}/arr/lidarr:/config"
      - "${DATA_BASE_PATH}:/data"
    restart: "unless-stopped"

  radarr:
    container_name: "radarr"
    image: "lscr.io/linuxserver/radarr:5.23.3.9987-ls275"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - "arr_default"
    ports:
      - "7878:7878"
    volumes:
      - "${DOCKER_BASE_PATH}/arr/radarr:/config"
      - "${DATA_BASE_PATH}:/data"
    restart: "unless-stopped"

  sonarr:
    container_name: "sonarr"
    image: "lscr.io/linuxserver/sonarr:4.0.14.2939-ls283"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - "arr_default"
    ports:
      - "8989:8989"
    volumes:
      - "${DOCKER_BASE_PATH}/arr/sonarr:/config"
      - "${DATA_BASE_PATH}:/data"
    restart: "unless-stopped"