name: immich

networks:
  proxy-netwerk:
    external: true
    name: "proxy-netwerk"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
    # --- NIEUWE REGEL ---
    # Maak de poort expliciet beschikbaar voor andere containers in het netwerk,
    # zonder deze te publiceren op de host.
    expose:
      - "2283"
    volumes:
      - ${IMMICH_UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_PASSWORD=${IMMICH_DB_PASSWORD}
      - DB_USERNAME=${IMMICH_DB_USERNAME}
      - DB_DATABASE_NAME=${IMMICH_DB_DATABASE_NAME}
      - TZ=${TZ}
      - REDIS_HOSTNAME=immich_redis
      - DATABASE_HOSTNAME=immich_postgres
      - NODE_ENV=production
      - IMMICH_REVERSE_PROXY_URL=https://fotos.mgdej.nl
    networks:
      - default
      - proxy-netwerk
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION}-armnn
    volumes:
      - model-cache:/cache
    environment:
      - TZ=${TZ}
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7662a54185593e74b09ce83d177
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      - POSTGRES_PASSWORD=${IMMICH_DB_PASSWORD}
      - POSTGRES_USER=${IMMICH_DB_USERNAME}
      - POSTGRES_DB=${IMMICH_DB_DATABASE_NAME}
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - ${IMMICH_DB_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
