name: pinchflat

networks:
  proxy-netwerk:
    external: true
    name: "proxy-netwerk"

services:
  pinchflat:
    container_name: pinchflat
    image: ghcr.io/kieraneglin/pinchflat:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - ${PINCHFLAT_CONFIG_LOCATION}:/config
      - ${YOUTUBE_MEDIA_LOCATION}:/downloads
    networks:
      - default
      - proxy-netwerk