version: "3.6"

networks:
  proxy-netwerk:
    external: true
    name: "proxy-netwerk"

services:
  glance:
    container_name: glance
    image: glanceapp/glance:latest
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-netwerk