# See the docs for more information: https://glanceapp.github.io/glance/
version: 1
server:
  # The host to bind to, defaults to 0.0.0.0
  host: 0.0.0.0
  # De poort is aangepast om conflicten te voorkomen
  port: 8081
# A list of pages to display in the dashboard
pages:
  # The first page to display
  - name: My Dashboard
    # --- GECORRIGEERDE STRUCTUUR ---
    # We voegen expliciet een 'columns' sectie toe.
    columns:
      - width: 100% # Een enkele kolom die de volledige breedte inneemt
        # Een lijst met rijen om weer te geven op de pagina
        rows:
          # De eerste rij
          - name: System
            # Een lijst met blokken om weer te geven in de rij
            blocks:
              # Het eerste blok
              - name: System
                type: system
                properties:
                  metrics:
                    - name: CPU
                      type: cpu
                    - name: Memory
                      type: memory
                    - name: Storage
                      type: storage
                      properties:
                        path: /
              - name: Docker
                type: docker
                properties:
                  containers:
                    - glance
          # De tweede rij
          - name: Links
            blocks:
              - name: Links
                type: links
                properties:
                  links:
                    - name: GitHub
                      url: https://github.com/glanceapp/glance
                    - name: Docs
                      url: https://glanceapp.github.io/glance/
