# See the docs for more information: https://glanceapp.github.io/glance/
version: 1
server:
  # The host to bind to, defaults to 0.0.0.0
  host: 0.0.0.0
  # De poort is aangepast om conflicten te voorkomen
  port: 8082
# A list of pages to display in the dashboard
pages:
  # The first page to display
  - name: Startpage
    width: slim
    hide-desktop-navigation: true
    center-vertically: true
    columns:
      - size: full
        widgets:
          - type: search
            autofocus: true

          - type: monitor
            cache: 1m
            title: Services
            sites:
              - title: Jellyfin
                url: https://yourdomain.com/
                icon: si:jellyfin
              - title: Gitea
                url: https://yourdomain.com/
                icon: si:gitea
              - title: qBittorrent # only for Linux ISOs, of course
                url: https://yourdomain.com/
                icon: si:qbittorrent
              - title: Immich
                url: https://yourdomain.com/
                icon: si:immich
              - title: AdGuard Home
                url: https://yourdomain.com/
                icon: si:adguard
              - title: Vaultwarden
                url: https://yourdomain.com/
                icon: si:vaultwarden

          - type: bookmarks
            groups:
              - title: General
                links:
                  - title: Gmail
                    url: https://mail.google.com/mail/u/0/
                  - title: Amazon
                    url: https://www.amazon.com/
                  - title: Github
                    url: https://github.com/
              - title: Entertainment
                links:
                  - title: YouTube
                    url: https://www.youtube.com/
                  - title: Prime Video
                    url: https://www.primevideo.com/
                  - title: Disney+
                    url: https://www.disneyplus.com/
              - title: Social
                links:
                  - title: Reddit
                    url: https://www.reddit.com/
                  - title: Twitter
                    url: https://twitter.com/
                  - title: Instagram
                    url: https://www.instagram.com/
