version: 1
server:
  # De poort is aangepast om conflicten te voorkomen
  port: 8082
pages:
  - name: Startpage
    width: slim
    hide-desktop-navigation: true
    center-vertically: true
    columns:
      - size: full
        widgets:
          - type: search
            autofocus: true

          - type: monitor
            cache: 1m
            title: Services
            sites:
              - title: Jellyfin
                url: https://jellyfin.mgdej.nl/
                icon: si:jellyfin
              - title: qBittorrent
                url: https://qbit.mgdej.nl/
                icon: si:qbittorrent
              - title: Immich
                url: https://immich.mgdej.nl/
                icon: si:immich

          - type: bookmarks
            groups:
              - title: General
                links:
                  - title: Gmail
                    url: https://mail.google.com/mail/u/0/
                  - title: Amazon
                    url: https://www.amazon.com/
                  - title: Github
                    url: https://github.com/